### ISSUE TITLE
configurable region for the GCP quickstart tutorial

### ISSUE THREAD

**Issue by cheers12** [teradici/cloud_deployment_scripts#108]
Can we have an field in the quickstart tutorial that allows users to change the GCP region that the CAM deployment is deployed in? May need some warning so that users will check if the region they are deploying has GPUs. Perhaps it can default to us-west2

**Comment by shermanyin** [comment]
The reason we didn't allow selection of region was because we have no control that the user would select a suitable region/zone where the specified GPU is available (if graphics workstations is selected).  With the new interactive GCP quickstart tutorial, we now support selection of regions since we added validation logic to ensure the user has the right resources / quota for the selected region.
