### ISSUE TITLE
Build state to image from?

### ISSUE THREAD

**Issue by infintropy** [teradici/cloud_deployment_scripts#148]
Hi I was wondering if these workstations should theoretically be possible to image and redeploy? I love building initial infrastructure with this, but ideally our team would deploy new workstations to ec2 from image via lambda/boto.

Currently, without any modifications after the terraform build, if I make an AMI from it, boot it into the same subnet-ws, and add it to CAM, when I go to connect in PCoiP client it only ever says "restarting remote workstation" and didnt does anything in EC2. Is there a guide for this? Our team had deployed a PCoIP solution earlier that imaged fine but was pointing to aws-marketplace-subscription— was hoping to emulate the same with CAM.

Thank you for any info, I really have appreciated your past help

**Comment by shermanyin** [comment]
Hi infintropy,

Thanks for using our scripts again.  These scripts are great for initial green field deployments and also to show you how it's done (by inspecting the terraform code and startup scripts).  The best way to expand number of workstations on top of the initially deployed ones are:
1) Go into the terraform.tfvars and increase the number of workstations you want (e.g. win_gfx_instance_count), then run terraform apply again.
2) Go to CAM at cam.teradici.com, under Workstations, click on the + sign and "Create new remote workstation".  If you want to deploy using code, you can also consider using CAM APIs, documented here: https://cam.teradici.com/api/docs.

Making AMIs out of deployed workstations is not going to work, because those workstations are already domain-joined and have their PCoIP agent registered with a PCoIP Registration Code.  What you could do to create an AMI is look at our provisioning scripts to understand what they do. Then:

1. Create a VM manually
2. Manually or through a user-data script, do the same setup as our provisioning.sh.tmpl file for that type of workstation, EXCEPT do NOT actually join the domain and install but do NOT register the PCoIP Agent.
3. Install any additional software / applications you want to be in the image.
4. If it is a windows instance, run sysprep to prepare it for snapshot.  Not sure if there is a CentOS equivalent.
5. Create an image/AMI from the instance
6. for new VMs created using the image, you will have to manually / have startup scripts to join the domain with the Domain Controller and register the PCoIP Agent with registration code.

May I ask which organization this is for?

Hope that helps.

**Comment by infintropy** [comment]
Very sorry for not responding sooner. 
This is for Nexodus vfx workstations. This helps tremendously!
